## Exercise 1: Convert a list and tuple into arrays

In [53]:
import numpy as np
A = 9
arr1 = np.array(9)
arr1 = np.arange(1,9)
arr2 = np.array([0,0,0,0,0,0,0,0])
Add = arr1+arr2
print("List to array: " ,end = '\n')
print(Add)
samp_tuple = [[8,4,6],[1,2,3]]
tuple_arr = np.array(samp_tuple)
tuple_arr1 = [[0,0,0],[0,0,0]]
tuple_arr1 = np.asarray(tuple_arr1)
tuple_arr = tuple_arr+tuple_arr1
print("Tuple to array:" ,end = '\n')
print(tuple_arr)

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
 [1 2 3]]


List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


## Also try np.asarray for the problem above! 

## Exercise 2:  Convert the values of Centigrade degrees into Fahrenheit degrees

In [58]:
import numpy as np
fval = [0,12,45.21,34,99.91]
print("Values in Fahrenheit degrees:")
farray = np.asarray(fval)
print(farray)
print("Values in Centigrade degrees:")
print((5*farray/9)-(5*32)/9)

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


## Exercise 3: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

In [74]:
import sys
sun = [1,2,3]
earray = np.asarray(sun, dtype=np.float64)
print("Size of the array: " ,np.size(earray))
print("Length of one array element in bytes: " ,earray.itemsize)
print("Total bytes consumed by the elements of the array: " ,np.size(earray)*earray.itemsize)


Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


## Exercise 4: Get the unique elements of an array

In [78]:
import numpy as np
oarray = [10,10,20,20,30,30]
print("Original array: " ,end= '\n')
print(np.asarray(oarray))
print("Unique elements of the above array:", end='\n')
print(np.unique(oarray))
marray = [[1,1],[2,3]]
print("Original array: " ,end='\n')
print(np.asarray(marray))
print("Unique elements of the above array:",end='\n')
print(np.unique(marray))

Original array: 
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array: 
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


## Exercise 5: Change the dimension of an array


In [82]:
import numpy as np
carray = [1,2,3,4,5,6,7,8,9]
print("Original array:",end='\n')
print(np.array(carray))
shape = np.array(carray).reshape(3,3)
print("Change array shape to (3, 3) -> 3 rows and 3 columns")
print(shape)

Original array:
[1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercise 6: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [83]:
import numpy as np
lnsp = np.linspace(2.5,6.5,30)
print(np.array(lnsp))

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


## Exercise 7: Convert 1-D arrays as columns into a 2-D array

In [92]:
import numpy as np
array1 = [10,20,30]
array2 = [40,50,60]
print("Array1: ",np.array(array1))
print("Array2: ",np.array(array2))
array2d = [array1,array2]
array2d = np.array(array2d)
print("Converted array" ,end='\n')
print(np.stack((array2d),axis = 1))

Array1:  [10 20 30]
Array2:  [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]


Array1: [10 20 30]
Array2: [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]


## Exercise 8: Create a 5x5 matrix with row values ranging from 0 to 4

In [20]:
import numpy as np
orray = np.zeros((5,5))
print("Original array: " ,end='\n')
print(orray)
#rarray = np.array([0,1,2,3,4,0,1,2,3,4,0,1,2,3,4,0,1,2,3,4,0,1,2,3,4])
print("Row values ranging from 0 to 4.", end='\n')
#rarray = np.arange(5)
orray += np.arange(5) 
print(orray)
#print(rarray.reshape((5,5)))
#orray[0: ,1:5] = 
#a = np.arange(5).reshape((5,5))
#a



Original array: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Exercise 9: Sum of all the multiples of 3 or 5 below 100

In [35]:
import numpy as np
tmp = np.array(range(3,100,3))
fmp = np.array(range(5,100,5))
totmp = np.concatenate((tmp,fmp))
finalmp = np.unique(totmp)
print(finalmp)
print(finalmp.sum())



[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


## Exercise 10: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [53]:
import numpy as np
x = np.arange(4)
print("One dimensional array:" ,end='\n')
print(x)
y = np.array([[0,1,2,3],[4,5,6,7]])
print("Two dimensional array:",end='\n')
print(y)
for a,b in np.nditer([x,y]):
    print(f'{a}:{b}')
    

One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


In [28]:
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

0
0
1
1
2
2
3
3


One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


## Exercise 11: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

In [56]:
import numpy as np
d = np.array([0.42436315, 0.48558583, 0.32924763, 0.7439979, 0.58220701, 0.38213418, 0.5097581, 0.34528799, 0.1563123])
print("Original array:")
print(np.reshape(d,(3,3)))
d = np.reshape(d,(1,9))
d = np.where(d>.5,.5,d)
print("Replace all elements of the said array with .5 which are greater than .5")
print(np.reshape(d,(3,3)))

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


## Exercise 12: Add a new row to an empty numpy array

In [63]:
import numpy as np
eptyar = np.array(range(0,0))
print("Empty array: ")
print(eptyar)
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
eptyar = np.stack((arr1,arr2))
print("After adding two new arrays:")
print(eptyar)

Empty array: 
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


## Exercise 13: Write a NumPy program to join a sequence of arrays along a new axis. 

In [102]:
import numpy as np
oriar = np.array([1,2,3])
oriar1 = np.array([2,3,4])
print("Original arrays:")
print(oriar)
print(oriar1)
#print(np.stack(oriar,axis = 0)) 
#print(np.vstack(oriar))
#print(np.reshape(oriar,(2,3)))
print("Sequence of arrays along a new axis:")
print(np.stack((oriar,oriar1),axis = 0))
print("Original arrays:")
print(np.vstack(oriar))
print('\n')
print(np.vstack(oriar1))
print("Sequence of arrays along a new axis:")
#print(np.vstack((oriar,oriar1)))
oriar2 = np.concatenate((oriar,oriar1))
print(np.vstack(oriar2))

Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]
Original arrays:
[[1]
 [2]
 [3]]


[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]

Original arrays:
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
